spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MEMBER-SERVICE
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
        - id: GROUP-SERVICE
          uri: lb://GROUP-SERVICE
          predicates:
            - Path=/group/**, /meeting/**
        - id: JWT-SERVICE
          uri: lb://JWT-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /user/getUser/**

server:
  port: 9191

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka